// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RezerwacjeKawiarnia.Api.Data;

#nullable disable

namespace RezerwacjeKawiarnia.Api.Migrations
{
    [DbContext(typeof(KawiarniaDbContext))]
    [Migration("20260313094246_DodanieRezerwacji")]
    partial class DodanieRezerwacji
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RezerwacjeKawiarnia.Api.Entities.Rezerwacja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataDo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataOd")
                        .HasColumnType("datetime2");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StolikId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StolikId");

                    b.ToTable("Rezerwacje");
                });

            modelBuilder.Entity("RezerwacjeKawiarnia.Api.Entities.Stolik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CzyZarezerwowany")
                        .HasColumnType("bit");

                    b.Property<int>("LiczbaMiejsc")
                        .HasColumnType("int");

                    b.Property<int>("Numer")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Stoliki");
                });

            modelBuilder.Entity("RezerwacjeKawiarnia.Api.Entities.Rezerwacja", b =>
                {
                    b.HasOne("RezerwacjeKawiarnia.Api.Entities.Stolik", "Stolik")
                        .WithMany("Rezerwacje")
                        .HasForeignKey("StolikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stolik");
                });

            modelBuilder.Entity("RezerwacjeKawiarnia.Api.Entities.Stolik", b =>
                {
                    b.Navigation("Rezerwacje");
                });
#pragma warning restore 612, 618
        }
    }
}
