// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RezerwacjeKawiarnia.Api.Data;

#nullable disable

namespace RezerwacjeKawiarnia.Api.Migrations
{
    [DbContext(typeof(KawiarniaDbContext))]
    partial class KawiarniaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RezerwacjeKawiarnia.Api.Entities.Stolik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CzyZarezerwowany")
                        .HasColumnType("bit");

                    b.Property<int>("LiczbaMiejsc")
                        .HasColumnType("int");

                    b.Property<int>("Numer")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Stoliki");
                });
#pragma warning restore 612, 618
        }
    }
}
